#!/bin/bash

echo "=== Canvas Course Shell Generator - Simple Auth EC2 Deployment ==="
echo "This script will help you deploy the simple authentication version to EC2"
echo ""

# Instructions for the user
echo "DEPLOYMENT INSTRUCTIONS:"
echo "1. Copy this entire repository to your EC2 instance"
echo "2. Replace the existing /home/ubuntu/canvas-course-generator/ directory"
echo "3. Run the following commands on your EC2 instance:"
echo ""
echo "   sudo systemctl stop canvas-course-generator.service"
echo "   cd /home/ubuntu/canvas-course-generator"
echo "   npm install"
echo "   sudo systemctl start canvas-course-generator.service"
echo ""
echo "WHAT THIS VERSION INCLUDES:"
echo "✓ Simple authentication (admin / P@ssword01)"
echo "✓ No Okta integration required"
echo "✓ All Canvas course creation functionality"
echo "✓ Same dashboard and UI experience"
echo "✓ Works with your existing Canvas API token"
echo ""
echo "ENVIRONMENT VARIABLES:"
echo "The application will use these settings:"
echo "- VITE_SIMPLE_AUTH=true (enables simple login)"
echo "- Canvas API URL: https://dppowerfullearning.instructure.com/api/v1"
echo "- Canvas API Token: (your existing token)"
echo "- Database: (your existing PostgreSQL database)"
echo ""
echo "TESTING:"
echo "After deployment, visit https://shell.dpvils.org"
echo "Login with: admin / P@ssword01"
echo ""
echo "This version bypasses all Okta authentication issues and allows you to"
echo "test the Canvas course shell creation functionality immediately."